version: "3"
services:
  database:
    image: postgres
    env_file: config/database/.env

  cache:
    image: redis
    command: redis-server --requirepass password

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      ENVIRONMENT: development
      API_BASE: http://proxy/api

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: trace
      NAME: api
      DB_USER: username
      DB_PASS: password
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mckp
      CACHE_HOST: cache
      CACHE_PORT: 6379
      CACHE_PASS: password
      ENVIRONMENT: development
      JWT_SECRET: my little secret

  proxy:
    image: nginx
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
